<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CrockeryFactory.Application</RootNamespace>
    <AssemblyName>CrockeryFactory.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrockeryFactory.Domain\CrockeryFactory.Domain.csproj" />
    <ProjectReference Include="..\CrockeryFactory.Persistence\CrockeryFactory.Persistence.csproj" />
  </ItemGroup>

</Project>
