<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CrockeryFactory.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CrockeryFactory.Domain\CrockeryFactory.Domain.csproj" />
    <ProjectReference Include="..\..\src\CrockeryFactory.Persistence\CrockeryFactory.Persistence.csproj" />
  </ItemGroup>

</Project>
