import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import {
  CreateProductRequest,
  PagedResult,
  Product,
  ProductListItem,
  UpdatePricesRequest,
  UpdateProductRequest,
} from './api.types';

export interface ProductQuery {
  search?: string;
  includeInactive?: boolean;
  page?: number;
  pageSize?: number;
}

/** A product together with the ETag needed to update it. */
export interface ProductWithVersion {
  product: Product;
  etag: string | null;
}

@Injectable({ providedIn: 'root' })
export class ProductsService {
  private readonly http = inject(HttpClient);
  private readonly base = '/api/v1/products';

  list(query: ProductQuery): Promise<PagedResult<ProductListItem>> {
    let params = new HttpParams()
      .set('page', String(query.page ?? 1))
      .set('pageSize', String(query.pageSize ?? 25));

    if (query.search?.trim()) params = params.set('search', query.search.trim());
    if (query.includeInactive) params = params.set('includeInactive', 'true');

    return firstValueFrom(this.http.get<PagedResult<ProductListItem>>(this.base, { params }));
  }

  /**
   * Reads the ETag off the response, because the update below cannot be sent without it.
   * Fetching the product and its version separately would leave a window in which the
   * two disagree.
   */
  async get(id: string): Promise<ProductWithVersion> {
    const response = await firstValueFrom(
      this.http.get<Product>(`${this.base}/${id}`, { observe: 'response' }),
    );

    return { product: response.body!, etag: response.headers.get('ETag') };
  }

  /**
   * The Idempotency-Key is generated by the caller, once per form submission, and reused
   * across retries of that submission. A fresh key per retry would defeat the mechanism
   * and create a second product.
   */
  create(request: CreateProductRequest, idempotencyKey: string): Promise<Product> {
    return firstValueFrom(
      this.http.post<Product>(this.base, request, {
        headers: new HttpHeaders({ 'Idempotency-Key': idempotencyKey }),
      }),
    );
  }

  /** If-Match carries the version read at load time; a stale one is refused with 409. */
  update(id: string, request: UpdateProductRequest, etag: string): Promise<Product> {
    return firstValueFrom(
      this.http.put<Product>(`${this.base}/${id}`, request, {
        headers: new HttpHeaders({ 'If-Match': etag }),
      }),
    );
  }

  updatePrices(id: string, request: UpdatePricesRequest): Promise<Product> {
    return firstValueFrom(this.http.put<Product>(`${this.base}/${id}/prices`, request));
  }

  deactivate(id: string): Promise<unknown> {
    return firstValueFrom(this.http.post(`${this.base}/${id}/deactivate`, {}));
  }
}
