// <auto-generated />
using System;
using CrockeryFactory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrockeryFactory.Web.Data.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    partial class FactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrockeryFactory.Modules.Catalogue.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CapacityMl")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Products", "catalogue");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Catalogue.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Grade")
                        .IsUnique()
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("ProductPrices", "catalogue");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Production.Entities.ProductionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchReference")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<Guid?>("BreakageReasonCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityBroken")
                        .HasColumnType("int");

                    b.Property<int>("QuantityGood")
                        .HasColumnType("int");

                    b.Property<int>("QuantitySeconds")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("BreakageReasonCodeId");

                    b.HasIndex("EntryNumber")
                        .IsUnique();

                    b.HasIndex("EntryDate", "ProductId");

                    b.ToTable("ProductionEntries", "production", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionEntry_NonNegative", "[QuantityGood] >= 0 AND [QuantitySeconds] >= 0 AND [QuantityBroken] >= 0");
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("OpeningBalanceAsOf")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Customers", "sales");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("DispatchDate")
                        .HasColumnType("date");

                    b.Property<string>("DispatchNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchDate");

                    b.HasIndex("DispatchNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId", "DispatchDate");

                    b.ToTable("Dispatches", "sales");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.DispatchLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<decimal>("LineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProductCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId", "LineNumber")
                        .IsUnique();

                    b.ToTable("DispatchLines", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_DispatchLine_PositiveQty", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("PaymentNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId", "PaymentDate");

                    b.ToTable("Payments", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_PositiveAmount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Stock.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AdjustedOn")
                        .HasColumnType("date");

                    b.Property<string>("AdjustmentNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<Guid>("ReasonCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentNumber")
                        .IsUnique();

                    b.HasIndex("ReasonCodeId");

                    b.HasIndex("ProductId", "Grade", "AdjustedOn");

                    b.ToTable("StockAdjustments", "stock");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Stock.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMovementAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProductId", "Grade");

                    b.ToTable("StockBalances", "stock", t =>
                        {
                            t.HasCheckConstraint("CK_StockBalance_NonNegative", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Stock.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReasonCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("ReasonCodeId");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.HasIndex("ProductId", "Grade", "OccurredOn");

                    b.ToTable("StockMovements", "stock");
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValues")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditEntries", "shared");
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Entities.FactorySetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Key");

                    b.ToTable("FactorySettings", "shared");

                    b.HasData(
                        new
                        {
                            Key = "Factory.Name",
                            Description = "Printed on every document header.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "Crockery Factory"
                        },
                        new
                        {
                            Key = "Factory.Address",
                            Description = "Printed under the factory name.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = ""
                        },
                        new
                        {
                            Key = "Factory.Phone",
                            Description = "Printed on dispatch documents.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = ""
                        },
                        new
                        {
                            Key = "Grades.Enabled",
                            Description = "Comma-separated QualityGrade values in use. A grade not listed is rejected with GRADE_NOT_ENABLED.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "1,2"
                        },
                        new
                        {
                            Key = "Document.Prefix.Dispatch",
                            Description = "Dispatch number prefix.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "D"
                        },
                        new
                        {
                            Key = "Document.Prefix.Production",
                            Description = "Production entry number prefix.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "P"
                        },
                        new
                        {
                            Key = "Document.Prefix.Payment",
                            Description = "Payment receipt number prefix.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "R"
                        },
                        new
                        {
                            Key = "Document.Prefix.Adjustment",
                            Description = "Stock adjustment number prefix.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "A"
                        },
                        new
                        {
                            Key = "Backdate.Days.Production",
                            Description = "Days a production entry may be backdated.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "7"
                        },
                        new
                        {
                            Key = "Backdate.Days.Dispatch",
                            Description = "Days a dispatch may be backdated.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "7"
                        },
                        new
                        {
                            Key = "Backdate.Days.Payment",
                            Description = "Days a payment may be backdated.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "30"
                        },
                        new
                        {
                            Key = "Backdate.Days.Adjustment",
                            Description = "Days a stock adjustment may be backdated.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "30"
                        },
                        new
                        {
                            Key = "Dispatch.Cancellation.MaxDays",
                            Description = "A dispatch older than this cannot be cancelled - CANCELLATION_TOO_LATE.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "90"
                        },
                        new
                        {
                            Key = "Production.LossWarningPercent",
                            Description = "Loss above this returns LOSS_UNUSUALLY_HIGH as a warning. It never blocks the entry.",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByUserId = new Guid("00000000-0000-0000-0000-00000000513e"),
                            Value = "25"
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Entities.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt");

                    b.ToTable("IdempotencyRecords", "shared");
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Entities.ReasonCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.HasIndex("Type", "IsActive", "SortOrder");

                    b.ToTable("ReasonCodes", "shared");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f00000-0000-0000-0000-000000000001"),
                            Code = "CRACK",
                            Description = "Cracked in firing",
                            IsActive = true,
                            SortOrder = 1,
                            Type = "Breakage"
                        },
                        new
                        {
                            Id = new Guid("a1f00000-0000-0000-0000-000000000002"),
                            Code = "WARP",
                            Description = "Warped",
                            IsActive = true,
                            SortOrder = 2,
                            Type = "Breakage"
                        },
                        new
                        {
                            Id = new Guid("a1f00000-0000-0000-0000-000000000003"),
                            Code = "GLAZE",
                            Description = "Glaze fault",
                            IsActive = true,
                            SortOrder = 3,
                            Type = "Breakage"
                        },
                        new
                        {
                            Id = new Guid("a1f00000-0000-0000-0000-000000000004"),
                            Code = "HANDLE",
                            Description = "Handle failure",
                            IsActive = true,
                            SortOrder = 4,
                            Type = "Breakage"
                        },
                        new
                        {
                            Id = new Guid("a1f00000-0000-0000-0000-000000000005"),
                            Code = "OTHER",
                            Description = "Other",
                            IsActive = true,
                            SortOrder = 99,
                            Type = "Breakage"
                        },
                        new
                        {
                            Id = new Guid("a2f00000-0000-0000-0000-000000000001"),
                            Code = "COUNT",
                            Description = "Physical count correction",
                            IsActive = true,
                            SortOrder = 1,
                            Type = "StockAdjustment"
                        },
                        new
                        {
                            Id = new Guid("a2f00000-0000-0000-0000-000000000002"),
                            Code = "DAMAGE",
                            Description = "Damaged in store",
                            IsActive = true,
                            SortOrder = 2,
                            Type = "StockAdjustment"
                        },
                        new
                        {
                            Id = new Guid("a2f00000-0000-0000-0000-000000000003"),
                            Code = "SAMPLE",
                            Description = "Issued as sample",
                            IsActive = true,
                            SortOrder = 3,
                            Type = "StockAdjustment"
                        },
                        new
                        {
                            Id = new Guid("a2f00000-0000-0000-0000-000000000004"),
                            Code = "OPENING",
                            Description = "Opening balance",
                            IsActive = true,
                            SortOrder = 4,
                            Type = "StockAdjustment"
                        },
                        new
                        {
                            Id = new Guid("a2f00000-0000-0000-0000-000000000005"),
                            Code = "OTHER",
                            Description = "Other",
                            IsActive = true,
                            SortOrder = 99,
                            Type = "StockAdjustment"
                        },
                        new
                        {
                            Id = new Guid("a3f00000-0000-0000-0000-000000000001"),
                            Code = "TRANSIT",
                            Description = "Damaged in transit",
                            IsActive = true,
                            SortOrder = 1,
                            Type = "SalesReturn"
                        },
                        new
                        {
                            Id = new Guid("a3f00000-0000-0000-0000-000000000002"),
                            Code = "WRONG",
                            Description = "Wrong item supplied",
                            IsActive = true,
                            SortOrder = 2,
                            Type = "SalesReturn"
                        },
                        new
                        {
                            Id = new Guid("a3f00000-0000-0000-0000-000000000003"),
                            Code = "QUALITY",
                            Description = "Quality complaint",
                            IsActive = true,
                            SortOrder = 3,
                            Type = "SalesReturn"
                        },
                        new
                        {
                            Id = new Guid("a3f00000-0000-0000-0000-000000000004"),
                            Code = "OTHER",
                            Description = "Other",
                            IsActive = true,
                            SortOrder = 99,
                            Type = "SalesReturn"
                        },
                        new
                        {
                            Id = new Guid("a4f00000-0000-0000-0000-000000000001"),
                            Code = "ENTRY",
                            Description = "Data entry error",
                            IsActive = true,
                            SortOrder = 1,
                            Type = "DispatchCancellation"
                        },
                        new
                        {
                            Id = new Guid("a4f00000-0000-0000-0000-000000000002"),
                            Code = "ORDER",
                            Description = "Order cancelled",
                            IsActive = true,
                            SortOrder = 2,
                            Type = "DispatchCancellation"
                        },
                        new
                        {
                            Id = new Guid("a4f00000-0000-0000-0000-000000000003"),
                            Code = "VEHICLE",
                            Description = "Vehicle not loaded",
                            IsActive = true,
                            SortOrder = 3,
                            Type = "DispatchCancellation"
                        },
                        new
                        {
                            Id = new Guid("a4f00000-0000-0000-0000-000000000004"),
                            Code = "OTHER",
                            Description = "Other",
                            IsActive = true,
                            SortOrder = 99,
                            Type = "DispatchCancellation"
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "b0000000-role-owner-stamp-000000000001",
                            Description = "Full access, including prices, catalogue and historical cancellations.",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "b0000000-role-clerk-stamp-000000000002",
                            Description = "Records production, dispatches, payments and stock adjustments.",
                            Name = "Clerk",
                            NormalizedName = "CLERK"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            ConcurrencyStamp = "b0000000-role-admin-stamp-000000000003",
                            Description = "Manages users, settings and audit. No transaction entry.",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("CrockeryFactory.Shared.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000513e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00000000-system-concurrency-stamp-01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            FullName = "System",
                            IsActive = false,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedUserName = "SYSTEM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-system-security-stamp-0001",
                            TwoFactorEnabled = false,
                            UserName = "system"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "auth");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Catalogue.Entities.ProductPrice", b =>
                {
                    b.HasOne("CrockeryFactory.Modules.Catalogue.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Production.Entities.ProductionEntry", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Entities.ReasonCode", "BreakageReasonCode")
                        .WithMany()
                        .HasForeignKey("BreakageReasonCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BreakageReasonCode");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Dispatch", b =>
                {
                    b.HasOne("CrockeryFactory.Modules.Sales.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.DispatchLine", b =>
                {
                    b.HasOne("CrockeryFactory.Modules.Sales.Entities.Dispatch", "Dispatch")
                        .WithMany("Lines")
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Payment", b =>
                {
                    b.HasOne("CrockeryFactory.Modules.Sales.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Stock.Entities.StockAdjustment", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Entities.ReasonCode", "ReasonCode")
                        .WithMany()
                        .HasForeignKey("ReasonCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReasonCode");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Stock.Entities.StockMovement", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Entities.ReasonCode", "ReasonCode")
                        .WithMany()
                        .HasForeignKey("ReasonCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReasonCode");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrockeryFactory.Shared.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CrockeryFactory.Shared.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Catalogue.Entities.Product", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("CrockeryFactory.Modules.Sales.Entities.Dispatch", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
